# Generated by Django 5.2.9 on 2026-01-08 11:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('invited', 'Invited')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'joined_at'], name='projects_pr_user_id_18afed_idx'),
        ),
    ]
