# Generated by Django 5.2.9 on 2026-01-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_created_at'),
    ]

    operations = [
    ]
