# Generated by Django 5.2.9 on 2026-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectmember',
            name='projects_pr_user_id_18afed_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('root', 'Root Admin'), ('admin', 'Admin'), ('user', 'User')], max_length=10),
        ),
    ]
